### ISSUE TITLE
لا اجد تحزيم حديث 

### ISSUE THREAD

**Issue by NouziMoggar** [parmaja/minilib#8]

**Comment by zaher** [comment]
لا يوجد تحزيم للمصدر، يمكنك استخدام ال git للحصول على اخر التحديثات من ال master أو الحصول على اخر نسخة مستقلة من ال release

**Comment by NouziMoggar** [comment]
شكرا

في الأحد، 16 جانفي 2022 14:11 Zaher Dirkey ***@***.***> كتب:
