### ISSUE TITLE
compile error on lazarus 2.3

### ISSUE THREAD

**Issue by alas82** [parmaja/minilib#9]
hello 
i try to compile on Lazarus 2.3 i got below messages 
Compile package MiniLib 1.0.2: Exit code 1, Errors: 3, Warnings: 2, Hints: 2
Hint: Start of reading config file C:\lazarus\fpc\bin\x86_64-win64\fpc.cfg
Hint: End of reading config file C:\lazarus\fpc\bin\x86_64-win64\fpc.cfg
Verbose: Free Pascal Compiler version 3.2.2-rrelease_3_2_2-0-g0d122c4953 [2023/01/22] for x86_64
Verbose: Copyright (c) 1993-2021 by Florian Klaempfl and others
Verbose: Target OS: Win64 for x64
Verbose: Compiling MiniLib.pas
Verbose: Compiling HejriDates.pas
Verbose: Compiling HejriUtils.pas
Verbose: Compiling UniDates.pas
Verbose: Compiling mnClasses.pas
mnClasses.pas(12,2) Warning: Illegal compiler switch "FUNCTIONREFERENCES+"
mnClasses.pas(12,34) Warning: Illegal compiler switch "ANONYMOUSFUNCTIONS+"
mnClasses.pas(26,11) Error: Identifier not found "Reference"
mnClasses.pas(26,21) Error: Error in type definition
mnClasses.pas(26,21) Error: Syntax error, ";" expected but "TO" found
Verbose: Compilation aborted
Verbose: C:\lazarus\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode

please advise

**Comment by zaher** [comment]
Use FPC 3.3.1 or above

**Comment by alas82** [comment]
how to get fpc 3.3.1 , as fcupdeluxe the highest version is 3.2.2 ?
